### Index method
GET http://localhost:3000/api/jokes

### Successfully posts a joke
POST http://localhost:3000/api/jokes
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjQ0MDY0MjMsInN1YiI6NH0.mpvhdu7pBpjgAuW8MVEAkCpBrYJr4i1f1LnK9654NBk

{
  "category_id": 1,
  "body": "The furniture store keeps calling me to come back, but all I wanted was one night stand."
}

### Unsuccessfully posts a joke
POST http://localhost:3000/api/jokes
Content-Type: application/json

{
  "body": "The furniture store keeps calling me to come back, but all I wanted was one night stand."
}

### Show first joke
GET http://localhost:3000/api/jokes/1


### Could not show 1000th joke
GET http://localhost:3000/api/jokes/1000


### Successfully update a joke
PUT http://localhost:3000/api/jokes/1
Content-Type: application/json

{
  "category_id": 2,
  "body": "Sample programming joke."
}

### Successfully delete first joke
DELETE http://localhost:3000/api/jokes/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjQ0MDc2MjEsInN1YiI6MX0.Z8Y-4gxDq788sX2GhG0Ql0Va7hDfa5UszExxFHJV63g


### Unsuccessfully delete first joke due to incorrect user
DELETE http://localhost:3000/api/jokes/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjQ0MDY0MjMsInN1YiI6NH0.mpvhdu7pBpjgAuW8MVEAkCpBrYJr4i1f1LnK9654NBk


### Unsuccessfully Delete 1000th joke
DELETE http://localhost:3000/api/jokes/1000


### Get random joke
GET http://localhost:3000/api/jokes/random?


### Add user
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
  "username": "John",
  "email": "john@test.com",
  "password": "password4",
  "password_confirmation": "password4"
}


### Check sign-in user
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
  "email": "ray@test.com",
  "password": "password1"
}

### Error for non-existing user or wrong password
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
  "email": "jared@test.com",
  "password": "password5"
}